---
title: "pdf_to_dataframe"
output: html_document
editor_options: 
  chunk_output_type: console
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
source(here("setup.R"))
```



```{libraries, echo = FALSE}

library(tidyverse) # includes stringr and dplyr
library(magrittr)
library(pdftools)
```


```{r}
text <- pdf_text(here("data/HQ-2016-00250-F Final Responsive Documents.pdf")) 

text[1:2]

# replace all line breaks ("\n") with a space
text %<>% str_replace_all("\n", " ")

# replace one or more spaces with a single space using the regular expression "+" for a pattern repeating one or more times
text %<>% str_replace_all(" +", " ")


text[1:2] 

text %<>% str_split("Title:")

# make it a tibble (a tidy data frame) 
d <- tibble(text = text)

d[1:2, ]

d %<>% unnest()


d

# split out additional columns
d %<>% 
  tidyr::separate(text, 
                  into = c("FROM", "Subject", "Control", "Assigned","Created", "Signature", "DATE", "Addressee", "Received", "Action", "Completed", "Priority", "Due", "Point of Contact", "Status"), 
                  sep = c("Subject:|Control:|Assigned To:|Created Date:|Signature Level:|Correspondence Date:|Addressee Office:|Received Date:|Action Requested:|Completed Date:|Priority:|Due Date:|Point of Contact:|Status:"), # RegEx pattern of separators
                  extra = "merge") # past any extra text at the end rather than dropping it

d %>% select(FROM, Subject, DATE)
```


Trim white space at the beginning and end of each cell with `trimws()`. Apply to all columns with `mutate_all()`.
```{r}
d %<>% mutate_all(trimws)

d %>% select(FROM, Subject, DATE)
```


Trim white space at the beginning and end of each cell with `trimws()`. Apply to all columns with `mutate_all()`.
```{r}
d %<>% write_csv(path = "DOE_HQ.csv")
```

