---
title: "Tidy campaign contributions by industry (using CRP and DIME data"
author: "Devin Judge-Lord"
output: html_document
---

```{r setup, echo = FALSE}
ssh -Y judgelord@linstat.ssc.wisc.edu
cd ../../../project/judgelord/correspondence
ls
git pull
R
source("setup.R")

# https://www.dropbox.com/s/m4bz7sbxebzowhp/GrimQuery.csv?dl=0
dime <- read_csv("data/GrimQuery.csv", col_names = FALSE)
```

# Compaign contributions from DIME
DIME SQL Query:
```{}
SELECT cycle, recipient_icpsr, recipient_type, recipient_name, recipient_icpsr, contributor_ext_id, bonica_rid, bonica_id2, contributor_category, sum(amount) AS sum_amount FROM newconts WHERE  recipient_type = 'CAND' AND seat IN ('federal:house', 'federal:senate') GROUP BY cycle, contributor_ext_id, recipient_icpsr INTO OUTFILE '/home/groups/andyhall/np_dime/GrimQuery.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
```

```{r data}
names(dime) <- c("cycle", "recipient_icpsr", "recipient_type", "recipient_name", "recipient_icpsr1", "contributor_ext_id", "bonica_rid", "bonica_id2", "contributor_category", "amount")

d <- dime
```

## Select Industry PACs

(see money-matching script for now)

For all contributions, skip this step.
```{r crp}
# Energy sector PACs
crp <- read_csv("CRP Data/crpEnergy.csv")
head(crp)

# New data just of contributions from selected industries
d %<>%
  filter(contributor_ext_id %in% crp$comid) %>%
  mutate(industry = "energy")
```

# Merge with voteview data
```{r voteview}
# merge with voteview data 
join_members <- . %>% 
  mutate(icpsr = as.numeric(recipient_icpsr)) %>% 
  right_join(members %>% 
               select(icpsr, bioname, congress) %>% 
               mutate(cycle = (congress - 107)*2 + 2000) %>% 
               distinct()
             ) %>% 
  # where a member is not observed in a cycle in DIME, replace ammount with na
  mutate(amount = replace_na(amount, 0))

d %<>% join_members()

# incpect 
nrow(d)
head(d)
```



# Tally contributions per member per cycle per industry 
```{r sumarize}
# sum up by ICPSR
d %<>%
  group_by(icpsr, congress, cycle, bioname, recipient_name) %>%
  tally(amount) %>%
  ungroup()
nrow(d)


d_other <- dime %>%
  # PACs not in industry
  filter(!contributor_ext_id %in% crp$comid) %>%
  mutate(industry = "other") %>% 
  join_members() %>% 
  group_by(icpsr, congress, cycle, bioname, recipient_name) %>%
  tally(amount) %>%
  ungroup()

nrow(d)

d %<>% full_join(d_other)

# Make sure there are indeed 0 counts if we expect them
d %>% 
  filter(amount == 0) %>%
  arrange(bioname)

d %>% 
  count(energyPAC)

# Any negative contribution amounts?
d %>% 
  filter(amount < 0)

# FIXME WHY NEGATIVES? 
# Change to positive
d %<>% 
  mutate(amount = abs(amount))

# inspect
head(d)  
nrow(d)

# problem names
d %>% 
  ungroup() %>% 
  mutate(bioname = toupper(bioname),
         recipient_name = toupper(recipient_name)) %>% 
  filter(str_sub(bioname, 1,3) != str_sub(recipient_name,1 , 3),
         cycle > 1999) %>% 
  filter(!str_detect("SANCHEZ", recipient_name)) %>% 
  mutate(wtf = !str_detect("SANCHEZ", recipient_name)) %>% 
  knitr::kable()
```





# Save results
```{r save}
pac_amounts <- d
save(pac_amounts, file = "data/pac_amounts.Rdata")
```

```
q()
n
git add "data/pac_amounts.Rdata"
git commit -m "add pac data"
git pull
git push

