# This script defines a function clean() for google sheets of correspondence logs that may have been hand coded
# It may also auto-code variables like TYPE based on agency-specific information

# Lots of errors, needs fixing

#file.name <- "ED" # for testing


clean <- function(file.name) {
  data <- gs_title(file.name) %>% gs_read() # get data

    #create agency column
  data$agency <- file.name
  
  # Format date, year, Congress
  data$DATE %<>% as.Date("%m/%d/%Y")
  data %<>% mutate(year = as.numeric(substring(DATE,1,4) ))
  data %<>% mutate(congress = as.numeric(round((year - 2001.1)/2)) + 107) # the 107th congress began in 2001
  
  
  # preprocess FROM column
  data$FROM <- gsub("the|The|honorable|Honorable", "", data$FROM)
  
  # create variable for first and last name
  data <- getFirstLast.Comma(data, 'FROM')
  
  # arrange columns for hand coding
  data %<>% select(ID, DATE,  FROM, everything())
  
  data%<>%
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("STUDENT LOAN QUESTION|STATUS CHECK|CONSTITUENT|CASEWORK|STUDENT LOAN REPAYMENT|FSA QUESTION|STUDENT LOAN INQUIRY|FOIA REQUEST|STUDENT LOAN DISCHARGE|STAFFER.*QUESTION|STAFFER.*REQUEST|FINANCIAL AID|LOAN FORGIVENESS|DISCHARGE APPLICATION|DEFAULTED STUDENT LOAN|SEEKING ASSISTANCE|REQUEST ASSISTANCE|HIS APPLICATION|STUDENT LOAN|HE OWES|STATUS UPDATE|REGARDING HIS|SHE IS|FSA2|FSA INFORMATION|NEED ASSISTANCE|HIGH SCHOOL|HER SON|HER DAUGHTER|HIS SON|HIS DAUGHTER|FAFSA|FERPA|REGARDING HER|CLAIMING|STUDENT AID|REPAYMENT OPTIONS|DISABILITY CASE|WOULD LIKE|LOAN QUESTION|UPDATE|FSA INQUIRY|SURVEY|HARASSMENT COMPLAINT|INQUIRY QUESTION|PARENTS.*CONCERNED|REQUESTING ASSISTANCE|SCHOLARSHIP|LOAN CONSOLIDATION|TUITION|PUBLICATION REQUEST|OCR COMPLAINT|APPEAL CASE|REPAYMENT|FOLLOW UP|FSA|FOLLOW-UP|DEBT|STATUS U|COMPLAINT AGAINST|FOREIGN SCHOOL", SUBJECT, ignore.case = TRUE), "1", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("STUDENT LOAN QUESTION|STATUS CHECK|CONSTITUENT|CASEWORK|STUDENT LOAN REPAYMENT|FSA QUESTION|STUDENT LOAN INQUIRY|FOIA REQUEST|STUDENT LOAN DISCHARGE|STAFFER.*QUESTION|STAFFER.*REQUEST|FINANCIAL AID|LOAN FORGIVENESS|DISCHARGE APPLICATION|DEFAULTED STUDENT LOAN|SEEKING ASSISTANCE|REQUEST ASSISTANCE|HIS APPLICATION|STUDENT LOAN|HE OWES|STATUS UPDATE|REGARDING HIS|SHE IS|FSA2|FSA INFORMATION|NEED ASSISTANCE|HIGH SCHOOL|HER SON|HER DAUGHTER|HIS SON|HIS DAUGHTER|FAFSA|FERPA|REGARDING HER|CLAIMING|STUDENT AID|REPAYMENT OPTIONS|DISABILITY CASE|WOULD LIKE|LOAN QUESTION|UPDATE|FSA INQUIRY|SURVEY|HARASSMENT COMPLAINT|INQUIRY QUESTION|PARENTS.*CONCERNED|REQUESTING ASSISTANCE|SCHOLARSHIP|LOAN CONSOLIDATION|TUITION|PUBLICATION REQUEST|OCR COMPLAINT|APPEAL CASE|REPAYMENT|FOLLOW UP|FSA|FOLLOW-UP|DEBT|STATUS U|COMPLAINT AGAINST|FOREIGN SCHOOL", SUBJECT, ignore.case = TRUE), "1", CERTAINTY)) %>%
  mutate(TYPE = ifelse (!grepl("[0-9]", ALT_TYPE) & grepl("LANGSTON UNIVERSITY|COMMUNITY COLLEGE|TEACHING AMERICAN HISTORY|INVESTING IN INNOVATION|RACE TO THE TOP|IMPROVEMENT OF POSTSECONDARY|BEHALF.*UNIVERSITY|CAROL M. WHITE|PROMISE NEIGHBORHOOD|PROGRAM APPLICATION|ON BEHALF OF.*GRANT APPLICATION|GRANT APPLICATION|SUPPORT FOR GRANT|UPWARD BOUND|ON BEHALF OF.*COLLEGE|CITY SCHOOLS|ENHANCEMENT|ON BEHALF OF.*SCHOOL", SUBJECT, ignore.case = TRUE), "3", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("LANGSTON UNIVERSITY|COMMUNITY COLLEGE|TEACHING AMERICAN HISTORY|INVESTING IN INNOVATION|RACE TO THE TOP|IMPROVEMENT OF POSTSECONDARY|BEHALF.*UNIVERSITY|CAROL M. WHITE|PROMISE NEIGHBORHOOD|PROGRAM APPLICATION|ON BEHALF OF.*GRANT APPLICATION|GRANT APPLICATION|SUPPORT FOR GRANT|UPWARD BOUND|ON BEHALF OF.*COLLEGE|CITY SCHOOLS|ENHANCEMENT|ON BEHALF OF .*SCHOOL", SUBJECT, ignore.case = TRUE), "1", CERTAINTY)) %>%
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("STUDENT LOAN PROGRAM", SUBJECT, ignore.case = TRUE), "1", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("STUDENT LOAN PROGRAM", SUBJECT, ignore.case = TRUE), "2", CERTAINTY)) %>%
  mutate(ALT_TYPE = ifelse (!grepl("[0-9]", ALT_TYPE) & grepl("STUDENT LOAN PROGRAM", SUBJECT, ignore.case = TRUE), "5", ALT_TYPE)) %>%
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("PUBLIC SCHOOLS", SUBJECT, ignore.case = TRUE), "3", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("PUBLIC SCHOOLS", SUBJECT, ignore.case = TRUE), "2", CERTAINTY)) %>%
  mutate(ALT_TYPE = ifelse (!grepl("[0-9]", ALT_TYPE) & grepl("PUBLIC SCHOOLS", SUBJECT, ignore.case = TRUE), "1", ALT_TYPE)) %>%
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("GLASGOW SCHOOL|JACOB JAVIT", SUBJECT, ignore.case = TRUE), "3", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("GLASGOW SCHOOL|JACOB JAVIT", SUBJECT, ignore.case = TRUE), "3", CERTAINTY)) %>%
  mutate(ALT_TYPE = ifelse (!grepl("[0-9]", ALT_TYPE) & grepl("GLASGOW SCHOOL|JACOB JAVIT", SUBJECT, ignore.case = TRUE), "1", ALT_TYPE)) %>%
  mutate(TYPE = ifelse (grepl("COMPANY WOULD LIKE", SUBJECT, ignore.case = TRUE), "2", TYPE)) %>%
  mutate(CERTAINTY = ifelse (grepl("COMPANY WOULD LIKE", SUBJECT, ignore.case = TRUE), "1", CERTAINTY)) 
  
  
  
  
  
  
  
  
  
  
  
}
