---
title: "pdf_to_dataframe"
output: html_document
editor_options: 
  chunk_output_type: console
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
source(here("setup.R"))
```



```{libraries, echo = FALSE}

library(tidyverse) # includes stringr and dplyr
library(magrittr)
library(pdftools)
```


```{r}
text <- pdf_text(here("data/DOE 2015-2018 part 3.pdf", "data/DOE 2015-2018 part 6.pdf", "data/DOE 2015-2018 part 8.pdf", "data/DOE 2015-2018 part 9.pdf", "data/DOE 2015-2018 part 11.pdf")) 

files<-list("data/DOE 2015-2018 part 3.pdf", "data/DOE 2015-2018 part 6.pdf", "data/DOE 2015-2018 part 8.pdf", "data/DOE 2015-2018 part 9.pdf", "data/DOE 2015-2018 part 11.pdf")

text <- map_raw(files, pdf_text)

pdf_tibble <- function(x){
  text <- pdf_text(x)
  d <- tibble(text = text)
  return(d)
}

d <- map_dfr(files, pdf_tibble)

text[1:2]

# replace all line breaks ("\n") with a space
d$text %<>% str_replace_all("\n", " ")

# replace one or more spaces with a single space using the regular expression "+" for a pattern repeating one or more times
d$text %<>% str_replace_all(" +", " ")


d$text[1:2] 

d$text %<>% str_split("Title:")



d[1:2, ]

d %<>% unnest()


d

# split out additional columns
d %<>% 
  tidyr::separate(text, 
                  into = c("FROM", "Subject", "Control", "Assigned","Created", "Signature", "DATE", "Addressee", "Received", "Action", "Completed", "Priority", "Due", "Point of Contact", "Status"), 
                  sep = c("Subject:|Control:|Assigned To:|Created Date:|Signature Level:|Correspondence Date:|Addressee Office:|Received Date:|Action Requested:|Completed Date:|Priority:|Due Date:|Point of Contact:|Status:"), # RegEx pattern of separators
                  extra = "merge") # past any extra text at the end rather than dropping it

d %>% select(FROM, Subject, DATE)
```


Trim white space at the beginning and end of each cell with `trimws()`. Apply to all columns with `mutate_all()`.
```{r}
d %<>% mutate_all(trimws)

d %>% select(FROM, Subject, DATE)
```


Trim white space at the beginning and end of each cell with `trimws()`. Apply to all columns with `mutate_all()`.
```{r}
d %<>% write_csv(path = "DOE_HQ 2015-2018.csv")
```

