---
title: "Lobbying the U.S. Federal Energy Regulatory Commission (FERC)"
output:
  pdf_document:
    keep_tex: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Rscript -e 'library(rmarkdown); rmarkdown::render("gh-pages/summary.Rmd", "html_document")'

requires <- c("tidyr", "broom", "knitr","ineq", "dplyr", "ggplot2", "magrittr", "stargazer", "maps", "fiftystater", "mapproj", "dotwhisker", "here")
  to_install <- c(requires %in% rownames(installed.packages()) == FALSE)
  install.packages(c(requires[to_install], "NA"), repos = "https://cloud.r-project.org/" )
  devtools::install_github("wmurphyrd/fiftystater")
  library(tidyverse)
  library(ineq)
  library(ggplot2); theme_set(theme_bw())
  library(magrittr)
  library(maps)
  library(fiftystater)
  library(mapproj)
  library(knitr)
  library(broom)
  library(dotwhisker)
  library(here)
```

```{r global.options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      cache = F, 
                      fig.width=8.5, 
                      split = T,
                      fig.align = 'center', 
                      fig.path='Figs/',
                      warning=FALSE, 
                      message=FALSE)
```

# Data
```{r data}
load(here("data/all_contacts.RData"))
# one obs per member per letter for all agencies
d <- all_contacts %>% 
  # define d as just FERC
  filter(agency=="DOE_FERC") %>% 
  select(-SUBJECT) %>% 
  mutate(majority = ifelse(majority == 1, "Majority", "Minority"))

# one obs per member per letter per committee for all agencies
load(here("data/all_contacts_committees.RData"))
# define dcommittees as just FERC
dcommittees <- all_contacts_committees %<>% filter(agency == "DOE_FERC")

# Coded letters, one obs per member per letter 
load(here("data/DOE_FERC-letters-coded.RData")) 
# TO DO: replace with DOE_FERC-letters-corps.Rdata when corps added
FERC_letters %<>% 
  select(ID, SUBJECT, 
         Freelancer, Cosigned_House, Cosigned_Senate,
         text_clean, Constituent, year,
         Place_State, Place_District, Place_District, 
         ProBusiness, AntiBusiness) %>% 
  distinct()

# merge in coded letters
d %<>% left_join(FERC_letters) %>% filter(year <2019)
```

In all, we have `r nrow(distinct(FERC_letters %>% select(ID)))` letters received by FERC and marked "congressional" since 1990. Most, but not all of these are from Members of the U.S. Congress. For this paper, we focus on `r nrow(distinct(FERC_letters %>% filter(year >1999) %>% select(ID) ) )` letters from 2000-2018. 

Many letters are cosigned, yeilding `r d %>% filter(year >1999, !is.na(bioname)) %>% nrow()` members-level observations for years `r min(d$year)`-`r max(d$year)`. 

---

## By party 


```{r part-constituent, fig.height=2}
d %>% 
  mutate(For = ifelse(tolower(Constituent) =="yes", "Constituent", NA),
         For = ifelse(!is.na(ProBusiness), "Business", For)) %>% 
  count(party, For, majority) %>% 
  filter(party != "(I)",
         !is.na(For),
         !is.na(majority)) %>% 
  ggplot() + 
  aes(y = n, x = party, fill = For) + 
  geom_col( position = "dodge") + 
  coord_flip() + facet_grid(. ~ majority) + 
  scale_fill_viridis_d(option = "A")
```

Some letters oppose businesses: 
```{r part-business, fig.height=2}
d %>% 
  mutate(position = ifelse(!is.na(ProBusiness), "ProBusiness", NA),
         position = ifelse(!is.na(AntiBusiness), "AntiBusiness", position)#,
         #position = ifelse(!is.na(AntiBusiness)&!is.na(ProBusiness), "Both", position),
         #position = ifelse(is.na(position)&!is.na(Constituent), "Neutral Constituent", position)
         ) %>% 
  count(party, position, majority) %>% 
  filter(party != "(I)",
         !is.na(position),
         !is.na(majority)) %>% 
  ggplot() + 
  aes(y = n, x = party, fill = position) + 
  geom_col( position = "dodge") + 
  coord_flip() + facet_grid(. ~ majority)+ 
  scale_fill_viridis_d(option = "C")
```

---

## Coding of constituent type 
Our coding of letter type is a mix of hand coding "Pro-business" and "Constituent" letters, as well as some coding rules applied to letters that were not put in either group by human coders (click `CODE` to see inductively-developed coding rules):
```{r code, eval=FALSE}
d %<>%
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("CONSTITUENT", SUBJECT, ignore.case = TRUE), 
                        "1", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("CONSTITUENT", SUBJECT, ignore.case = TRUE), 
                             "2", CERTAINTY)) %>%
  ## Corporate service?
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("ROCKIES EXPRESS PIPELINE|ELECTRIC GENERATOR PROJECT", SUBJECT, ignore.case = TRUE), 
                        "2", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("ROCKIES EXPRESS PIPELINE|ELECTRIC GENERATOR PROJECT", SUBJECT, ignore.case = TRUE), 
                             "3", CERTAINTY)) %>%
  ## or policy
  mutate(ALT_TYPE = ifelse (!grepl("[0-9]", ALT_TYPE) & grepl("ROCKIES EXPRESS PIPELINE|ELECTRIC GENERATOR PROJECT", SUBJECT, ignore.case = TRUE), 
                            "5", ALT_TYPE)) %>%
  ## Policy work
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("COMMENTS OF US SENATOR|REQUEST INFORMATION|SENATOR.*COMMENTS|HEARING|MEETING|US SENATE SUBMITS|OVERSIGHT OF THE|EXPRESSING CONCERNS|SENATE SUBMITS COMMENTS", SUBJECT, ignore.case = TRUE), 
                        "5", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("COMMENTS OF US SENATOR|REQUEST INFORMATION|SENATOR.*COMMENTS|HEARING|MEETING|US SENATE SUBMITS|OVERSIGHT OF THE|EXPRESSING CONCERNS|SENATE SUBMITS COMMENTS", SUBJECT, ignore.case = TRUE), 
                             "1", CERTAINTY)) %>%
  ## Local government
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("CITY OF.*APPLICATION|APPLICATION.*CITY OF|ON BEHALF OF.*COUNTY", SUBJECT, ignore.case = TRUE), 
                        "3", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("CITY OF.*APPLICATION|APPLICATION.*CITY OF|ON BEHALF OF.*COUNTY", SUBJECT, ignore.case = TRUE), 
                             "1", CERTAINTY)) %>%
  ## Corporate service
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("NEW COAL", SUBJECT, ignore.case = TRUE), 
                        "4", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("NEW COAL", SUBJECT, ignore.case = TRUE), 
                             "2", CERTAINTY)) %>%
  mutate(ALT_TYPE = ifelse (!grepl("[0-9]", ALT_TYPE) & grepl("NEW COAL", SUBJECT, ignore.case = TRUE), 
                            "5", ALT_TYPE)) %>%
  ## PUCs = nonprofits, right?
  mutate(TYPE = ifelse (!grepl("[0-9]", TYPE) & grepl("PUBLIC UTILITIES COMMISSION", SUBJECT, ignore.case = TRUE), 
                        "3", TYPE)) %>%
  mutate(CERTAINTY = ifelse (!grepl("[0-9]", CERTAINTY) & grepl("PUBLIC UTILITIES COMMISSION", SUBJECT, ignore.case = TRUE), 
                             "1", CERTAINTY)) 
```

FERC has an especially high ratio of letters written on behalf of businesses compared other agencies that mostly recieve letters from legislators on behalf of their constituents. 

```{r data-by-type}
d %<>%  
  mutate(Type = as.character(Type)) %>% 
  mutate(Type = ifelse(tolower(Constituent) =="yes", "Indiv. Constituent", Type)) %>% 
  mutate(Type = ifelse(!is.na(ProBusiness), "Corp. Constituent", Type)) 

d %>% 
  filter(Type != "To be coded") %>%  
  mutate(total = n()) %>% 
  group_by(Type, total) %>% summarise(nT = n()) %>% 
  mutate(percent = paste0(nT, " = ", 100*round(nT/total, 2), "%")) %>% 
  ggplot() + 
  geom_col(aes(x = Type, y = nT)) + 
  geom_text(aes(x = Type, y = nT, label = percent), vjust = -.1) +
  labs(x = "",
       y = paste("Number of Contacts, N =", sum(nrow(d))),
       title = "Legislator Contacts with FERC") +
  theme(panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x.top = element_text())
```

```{r data-by-type-all}
all_contacts %>% 
  mutate(Type = as.character(Type)) %>% 
  filter(Type != "To be coded") %>%  
  mutate(total = n()) %>% 
  group_by(Type, total) %>% summarise(nT = n()) %>% 
  mutate(percent = paste0(nT, " = ", 100*round(nT/total, 2), "%")) %>% 
  ggplot() + 
  geom_col(aes(x = Type, y = nT)) + 
  geom_text(aes(x = Type, y = nT, label = percent), vjust = -.1) +
  labs(x = "",
       y = paste("Number of Contacts, N =", sum(nrow(all_contacts))),
       title = "All Legislators Contacts with Federal Agencies") +
  theme(panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x.top = element_text())
```

---

### Senators vs. state population 

```{r population, fig.height= 3.7, fig.width=6}
d %>% 
  filter(chamber == "Senate") %>% 
    group_by(member_state, year, pop2010) %>% summarise(n = n()) %>%
    group_by(member_state, pop2010) %>% summarise(mean = mean(n)) %>% ungroup() %>% 
    ggplot() + 
    geom_point(aes(x = log(pop2010), y = mean), color = "light blue") + 
    geom_smooth(aes(x = log(pop2010), y = mean)) + 
  geom_text(aes(x = log(pop2010), y = mean, label = ifelse(mean > mean(mean)*1.75, member_state, "")), check_overlap = F, size = 2.5, hjust = 0) + theme_bw() +
  labs(title = "Senator Requests per Year by State Population",
       x = "Log State Population",
       y = "Average Number of Requests per Year")

```

```{r sentate_percapita_map}
Chamber = "Senate"

d %>% 
  filter(chamber == Chamber) %>% 
  group_by(state, Type) %>% summarise(n = n()) %>%
# map_id creates the aesthetic mapping to the state name column
ggplot() + 
  # map points to the fifty_states shape data
  geom_map(aes(map_id = state, fill = n), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "", title = paste("Total Number of Contacts from members of the", Chamber)) +
  theme(legend.position = "bottom", legend.title = element_blank(),
        panel.background = element_blank())# + facet_grid(. ~ Type)

d %>% 
  filter(chamber == Chamber) %>% 
  group_by(state, pop2010, Type) %>% summarise(n = n()) %>% ungroup() %>% 
  mutate(Per_Capita = n/pop2010*1000000) %>% 
  # map_id creates the aesthetic mapping to the state name column in your data
  ggplot() + 
  # map points to the fifty_states shape data
  geom_map(aes(map_id = state, fill = Per_Capita), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "", title = paste("Contacts Per Million Residents from Members of the", Chamber)) +
  theme(legend.position = "bottom", legend.title = element_blank(),
        panel.background = element_blank()) #+
  #facet_grid(. ~ Type)
```


---

### Members who contact FERC more than average: 

```{r members_barcoded, fig.height=4, fig.width=9}
# barcode plot of committee members 

Chamber <- "Senate" # "House" #  
 
# member by year by agency 
d %>% 
  filter(chamber == Chamber) %>% 
  group_by(name_state) %>% mutate(n = n()) %>% ungroup() %>% 
  filter(n > mean(n)) %>%
  ggplot() +
  geom_point(
    aes(x = DATE, 
        y = reorder(name_state, n) ), 
    # alpha = .6,
    shape = 73,
    size=2
  ) +  
  labs(title = paste(Chamber),
       y = paste("Members by", "Total Number of Letters"), 
       x = "Date of Correspondence" ) +
  theme(
    legend.title = element_blank(),
    axis.text.y = element_text(size=5)
  ) + 
    guides(fill=guide_legend(ncol=1)) 


Chamber <- "House" # "House" #  
 
# member by year by agency 
d %>% 
  filter(chamber == Chamber) %>% 
  group_by(name_state) %>% mutate(n = n()) %>% ungroup() %>% 
  filter(n > mean(n)) %>%
  ggplot() +
  geom_point(
    aes(x = DATE, 
        y = reorder(name_state, n) ), 
    # alpha = .6,
    shape = 73,
    size=2
  ) +  
  labs(title = paste(Chamber),
       y = paste("Members by", "Total Number of Letters"), 
       x = "Date of Correspondence" ) +
  theme(
    legend.title = element_blank(),
    axis.text.y = element_text(size=5)
  ) + 
    guides(fill=guide_legend(ncol=1)) 
```

### Members who contact FERC more, relative to other agencies: 
```{r ferc_vs_all_rate}
all_contacts %>%
  mutate(FERC = agency == "DOE_FERC") %>%
  group_by(chamber, FERC, name_state, state) %>%
  summarise(n = n() ) %>%
  ungroup() %>%
  spread(key = "FERC", value = "n") %>% 
  mutate(ShareToFERC = round(`TRUE`/(`TRUE`+`FALSE`),2) )%>% 
  arrange(-ShareToFERC) %>% 
  mutate(total = `TRUE` + `FALSE`) %>% 
  select(name_state, chamber, total, ShareToFERC) %>% 
  filter(ShareToFERC>.3) %>%
  knitr::kable()
```


### Members who contact FERC more in a Congress, relative to other agencies: 
```{r ferc_vs_all_rate_committees}
all_contacts %>%
  mutate(FERC = agency == "DOE_FERC") %>%
  group_by(congress, chamber, committees, FERC, name_state, state) %>%
  summarise(n = n() ) %>%
  ungroup() %>%
  spread(key = "FERC", value = "n") %>% 
  mutate(ShareToFERC = round(`TRUE`/(`TRUE`+`FALSE`),2) )%>% 
  arrange(-ShareToFERC) %>% 
  mutate(total = `TRUE` + `FALSE`) %>% 
  select(name_state, congress, chamber, committees, total, ShareToFERC) %>% 
  filter(ShareToFERC>.5) %>%
  knitr::kable()
```


## Interesting cases

In an article titled "Republican congressmen’s funding dwarfs challengers’", the Charleston Gazee-Mail noted how energy companies backed Representative Alex Mooney (R-WV). Indeed, Mooney wrote to FERC more than any other agency, always on behalf of energy projects, mostly pipelines. 
In 2017, he wrote on behalf of the 
Dominion Energy Supply Header Project,
National Fuel Gas Distribution Corporation's [Northern Access Project](https://www.natfuel.com/supply/NorthernAccess2016/default.aspx),
Transcontinental Gas Pipe Line Company's [Atlantic Sunrise Project](https://blog.williams.com/projects-and-operations/atlantic-sunrise/atlantic-sunrise-project-placed-into-full-service/), 
Columbia Gas Transmission's proposed Eastern Panhandle Expansion project,
Columbia's WB Xpress Project to build new compressor stations,
In 2015 he wrote on behalf of the
Columbia s Mountaineer XPress Project,
Atlantic Coast Pipeline ACP project. 
The parent companies of these projects spend millions of dollars on lobbying (Lobbyview). The WV Gazette reports funding from Dominion that is not included in Lobbyview totals. 

---


# Top companies in pro-business letters
```{r probusiness-letters}
# Split out to one obs per member per letter per business
dcorps <- d %>%
  mutate(ProBusiness = ProBusiness %>% str_split(";")) %>%
  unnest(ProBusiness)

dcorps %<>% mutate(ProBusiness = ProBusiness %>%
                     str_replace("RTO", 
                                 "Regional Transmission Organization") %>%  
         str_remove_all(" Company.*| \\(.*| Inc.*| LLC.*| Energy.*") )%>%
  mutate(AntiBusiness = AntiBusiness %>% 
           str_replace("RTO", 
                       "Regional Transmission Organization") %>%  
         str_remove_all(" Company.*| \\(.*| Inc.*| LLC.*| Energy.*") )

dcorps %>%
  filter(!is.na(ProBusiness),
         !str_detect(ProBusiness, "Regional Transmission Organization") ) %>%
  group_by(ProBusiness) %>%
  select(id, last_name, ProBusiness, ID) %>%
  distinct() %>%
  summarise( n = n() , 
             members = str_c(last_name, collapse = "; "),
             ID = str_c(unique(ID), collapse = "; ")) %>%
  filter(n>quantile(n,.9))%>%
  arrange(-n) %>%
  knitr::kable()
```


# Letters citing companies registered to lobby FERC
Of the companies registered to lobby FERC, several appear in the letter texts. Here `company_short` is a shortened version a name that refrences several affiliated companies, each of which are registered separatly. 
*TO DO:* 
- (1) Identify linked corporations for other top companies in the data
- (2) extract company contact persons and information from the FERC website.
```{r}
load(here("data", "DOE_FERC-corps.Rdata"))
FERC_corps %<>% ungroup() %>% group_by(company_short) %>% mutate(industry = str_c(unique(industry), collapse = ";")) %>% select(-company, -Fortune500) %>% distinct() 

## Make a single string of short corp names
ferc_short <- unique(FERC_corps$company_short) %>% 
  str_c(collapse = "|") %>% 
  str_remove_all("||")

# bad string? 
# str_detect("", ferc_short)

```


## Pro-business letters
```{r probusiness-letters-ferc}
dcorps %>%
  mutate(company_short = str_extract(ProBusiness, ferc_short)) %>%
  left_join(FERC_corps) %>% 
  distinct() %>%
  group_by(company_short_refs) %>%
  select(ID, last_name, company_short, company_short_refs) %>%
  filter(company_short != "")%>%
  distinct() %>%
  summarise( n = n() , 
             company_short = str_c(unique(company_short), collapse = "; "),
             members = str_c(last_name, collapse = "; "),
             ID = str_c(ID, collapse = "; ")) %>%
  filter(n>quantile(n,.9))%>%
  select(company_short, n, everything()) %>%
  arrange(-n) %>%
  knitr::kable()

## Longer list with company full names
# d %>%
#   mutate(company_short = str_extract(ProBusiness, ferc_short)) %>%
#   drop_na(company_short) %>%
#   mutate(members = paste(CongressPerson, Cosigned_House, Cosigned_Senate, sep = ";")) %>%
#   mutate(members = str_remove_all(members, ";NA")) %>%
#   group_by(company_short) %>%
#   mutate(members = str_c(unique(members), collapse = ";")) %>%
#   select(company_short, members) %>%  distinct() %>%
#   left_join(FERC_corps) %>% distinct() %>%
#   knitr::kable(caption = "Pro Businesses matching those registered with FERC")
```

## Anti-business letters

```{r antibusiness-letters-ferc}
dcorps %>%
  mutate(company_short = str_extract(AntiBusiness, ferc_short)) %>%
  left_join(FERC_corps) %>% 
  distinct() %>%
  group_by(company_short_refs) %>%
  select(ID, last_name, company_short, company_short_refs) %>%
  filter(company_short != "")%>%
  distinct() %>%
  summarise( n = n() , 
             company_short = str_c(unique(company_short), collapse = "; "),
             members = str_c(last_name, collapse = "; "),
             ID = str_c(ID, collapse = "; ")) %>%
  filter(n>quantile(n,.9))%>%
  select(company_short, n, everything()) %>%
  arrange(-n) %>%
  knitr::kable()

## Longer list with company full names
# d %>% 
#   mutate(company_short = str_extract(AntiBusiness, ferc_short)) %>% 
#   drop_na(company_short) %>% 
#   mutate(members = paste(CongressPerson, Cosigned_House, Cosigned_Senate, sep = ";")) %>%
#   mutate(members = str_remove_all(members, ";NA")) %>% 
#   group_by(company_short) %>% 
#   mutate(members = str_c(unique(members), collapse = ";")) %>% 
#   select(company_short, members) %>%  distinct() %>%
#   left_join(FERC_corps) %>% distinct() %>% 
#   knitr::kable(caption = "Anti Businesses matching those registered with FERC")

```


---

## Company lookup table

Clean companies names extracted from letters and create shortened name that is more likely to be found in other datasets.
```{r company-inspect, eval=FALSE}
# Split out to one obs per member per letter per business
dcorps <- d %>%
  select(ID, bioname, ProBusiness, AntiBusiness, Proproject, AntiProject) %>% 
  group_by(ID, bioname) %>% 
  gather(key = company, value = position) %>%
  mutate(company = company %>% str_split(";")) %>%
  unnest(ProBusiness)

dcorps %<>% mutate(ProBusiness = ProBusiness %>%
                     str_replace("RTO", 
                                 "Regional Transmission Organization") %>%  
         str_remove_all(" Company.*| \\(.*| Inc.*| LLC.*| Energy.*") )

dcorps$company %<>% 
  str_replace_all("\r\n", ", ") %>% 
  str_remove_all("^, ") %>%
  trimws() # trim white space before and after company names

dcorps %<>% 
  filter(nchar(company)>1) %>% # filter out names less than 2 characters 
  filter(!company %in% c("FERC Online Support", "Note:","LLC", "Transportation, LLC")) %>% # not companies
  filter(!str_detect(company, "[0-9]{2}/[0-9]{2}/[0-9]{4}")) %>% # dates not companies
  distinct() # drop duplicates

## For matching, remove endings like ", Inc." etc. 
trim <- function(d){
d %>%
  str_remove_all("Village of |\\(.*|,.*| -.*| Pipe.*| Company.*| Corp.*| Energy.*| Holdings.*| Gas$| Project.*| Co.| Gen.| LLC| L.L.C.|  L.P.| Inc.| L.P.| Ltd.| LP| Limited Partnership| Limited Liability| Transportation and Storage| Storage and Transportation") %>% 
  str_remove_all("^, ") %>%
  trimws()  # filter out names less than 2 characters 
}

FERC_corps$company_short <- trim(FERC_corps$company) %>% trim()

FERC_corps %<>% filter(nchar(company_short)>1,
                       company_short != "Â")

head(FERC_corps)
```


```{r, include = FALSE, eval=FALSE}
## Correct over-trimmed names
FERC_corps %<>% 
  mutate(company_short = ifelse(company == "Columbia Energy Power Marketing Corporation", "Columbia Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Michigan Energy Exchange, LLC", "Michigan Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Midwest Energy, Inc.", "Midwest Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Northwest Pipeline LLC", "Northwest Pipeline", company_short))%>%
  mutate(company_short = ifelse(company == "Peak Energy, Inc.", "Peak Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Public Service Company of New Mexico", "Public Service Company of New Mexico", company_short))%>%
  mutate(company_short = ifelse(company == "Salt Lake Energy Systems, LLC", "Salt Lake Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Natural Gas Pipeline Company of America", "Natural Gas Pipeline Company of America", company_short))%>%
  mutate(company_short = ifelse(company == "Natural Gas Trading Corporation", "Natural Gas Trading Corporation", company_short))%>%
  mutate(company_short = ifelse(company == "Energy, USA-TPC Corp.", "TPC", company_short))%>%
  mutate(company_short = ifelse(company == "New Energy Partners, L.L.C.", "New Energy Partners", company_short))%>%
  mutate(company_short = ifelse(company == "New Energy Service, LLC", "New Energy Service", company_short))%>%
  mutate(company_short = ifelse(company == "North Energy Associates, A Limited Partnership", "North Energy Associates", company_short))%>%
  mutate(company_short = ifelse(company == "Pipeline Company LLC", "Pipeline Company LLC", company_short))%>%
  mutate(company_short = ifelse(company == "Express Pipeline LLC", "Express Pipeline LLC", company_short))%>%
  mutate(company_short = ifelse(company == "American Energy Savings, Inc.", "American Energy Savings", company_short))%>%
  mutate(company_short = ifelse(company == "Electric Energy, Inc.", "Electric Energy, Inc.", company_short))%>%
  mutate(company_short = ifelse(company == "System Energy Resources, Inc., Llano Estacado Wind, LLC, System Energy Resources, Inc., Northern Iowa Windpower, LLC, and RS Cogen, L.L.C.", "System Energy Resources", company_short))%>%
  mutate(company_short = ifelse(company == "Public Service Company of Colorado", "Public Service Company of Colorado", company_short))%>%
  mutate(company_short = ifelse(company == "Southern Company Services, Inc.", "Southern Company", company_short))%>%
  mutate(company_short = ifelse(company == "International Energy Consultants", "International Energy Consultants", company_short))%>%
  mutate(company_short = ifelse(company == "Jackson Pipeline Company", "Jackson Pipeline", company_short))%>%
  mutate(company_short = ifelse(company == "Southern Energy California", "Southern Energy California", company_short))%>%
  mutate(company_short = ifelse(company == "Tennessee Gas Pipeline Company, L.L.C.", "Tennessee Gas Pipeline", company_short))%>%
  mutate(company_short = ifelse(company == "Select Energy New York, Inc.", "Select Energy New York", company_short))%>%
  mutate(company_short = ifelse(company == "Inland Corporation", "Inland Corporation", company_short))%>%
  mutate(company_short = ifelse(company == "Advanced Energy Systems, Inc.", "Advanced Energy Systems", company_short))%>%
  mutate(company_short = ifelse(company == "Consumers Energy Company", "Consumers Energy Company", company_short))%>%
  mutate(company_short = ifelse(company == "Boston Energy Trading and Marketing LLC", "Boston Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Complete Energy Services, Inc.", "Complete Energy Services", company_short))%>%
  mutate(company_short = ifelse(company == "El Paso Energy Intrastate, L.P.", "El Paso Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Houston Pipe Line Company LP", "Houston Pipe Line", company_short))%>%
  mutate(company_short = ifelse(company == "North American Energy, Inc.", "North American Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Spokane Energy, LLC", "Spokane Energy", company_short))%>%
  mutate(company_short = ifelse(company == "Salem Energy Systems, LLC", "Salem Energy", company_short))%>%
  mutate(company_short = ifelse(company_short == "Direct", "Direct Energy", company_short))%>%
  mutate(company_short = ifelse(company_short == "DC", "DC Energy", company_short))%>%
  mutate(company_short = ifelse(company_short == "PS", "PS Energy Group", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Coastal", "Coastal Pipeline", company_short)) %>%
  mutate(company_short = ifelse(company_short == "CT", "CT Corporation", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Forest", "Forest Pipeline", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Minnesota", "Minnesota Pipe Line", company_short)) %>%
  mutate(company_short = ifelse(company_short == "NW", "NW Pipeline", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Ohio River", "Ohio River Pipe Line", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Rio Grande", "Rio Grande Pipeline", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Plains", "Plains Pipeline", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Portland", "Portland Pipe Line", company_short)) %>%
  mutate(company_short = ifelse(company_short == "AP", "AP Holdings", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Ohio River", "Ohio River Pipe Line", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Boundary", "Boundary Gas", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Columbia", "Columbia Energy", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Independence", "Independence Energy Group", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Lakeside", "Lakeside Energy", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Mitchell", "Mitchell Energy", company_short)) %>%
  mutate(company_short = ifelse(company_short == "Stream", "Stream Energy", company_short))%>%
  mutate(company_short = ifelse(company_short == "AI", "AI Energy", company_short))

## Inspect over-trimmed company names
FERC_corps %>% filter(company_short %in% c("", "LLC", "Energy", "Pipeline", "Natural", "North", "New", "Express", "American", "Electric", "System", "Direct", "DC", "PS", "CT", "Forest", "International", "Tennessee", "Salt Lake", "Lakeside", "NW", "Jackson", "Public Service", "Peak", "Independence", "Select", "Portland", "Michigan", "Boundary", "Coastal", "Minnesota", "Midwest", "Columbia", "Plains", "Stream", "Mitchell", "AP", "Southern", "Ohio River", "Northwest", "Rio Grande", "AI", "Transportation", "12/20/2018", "Salem", "Boston", "Spokane", "El Paso", "Houston", "North American", "Consumers", "Advanced", "Complete", "Inland", "Limited Partnership", "RTO")) %>% select(company_short)

FERC_corps %>% filter(str_detect(company_short, ","))

FERC_corps %>% group_by(company_short) %>% tally() %>% arrange(-n) 

FERC_corps %>% group_by(company_short) %>% tally() %>% arrange(nchar(company_short)) %>% mutate(nchar = nchar(company_short))

FERC_corps %>% group_by(company_short) %>% tally() %>% arrange(-nchar(company_short)) 
```


---

## Committee Chairs

```{r committeechiars_barcode_senate, fig.height=10}
Chamber = "Senate"
dcommittees %>%  
  mutate(position = ifelse(position == "Other", NA, position)) %>% 
  filter(chamber == Chamber, 
         chair_since_2007 == T,  
         DATE < as.Date("2017-01-01"),
        DATE > as.Date("2007-01-01"),
        assigneddate < as.Date("2017-01-01"),
        terminationdate > as.Date("2007-01-01")) %>%
  select(DATE, chair, position, department, assigneddate, terminationdate, chamber, committee) %>% 
  ggplot() +
  geom_point(
    aes(x = DATE, 
        y = chair),
    shape = 73,
    size=2 
  ) +
  geom_segment(aes(y = chair, yend = chair, 
                   x = assigneddate, xend = terminationdate, 
                   linetype = factor(position)),
               position = position_nudge(y = -0.3)) +
  labs(title = paste(Chamber, "Committee Chairs"),
       y = "", 
       x = "" ) +
  scale_y_discrete(position = "right") +
  theme(
    strip.text.y = element_text(angle = 180, size = 5),
    legend.title = element_blank(),
    axis.text.y = element_text(size=5),
    axis.text.x = element_text(angle = 0)
  ) + 
  facet_grid(committee ~ ., scales = "free_y", space = "free_y", switch = "both") 
```

```{r committeechiars_barcode_house, fig.height=10, include= TRUE}
Chamber = "House"
dcommittees %>%  
  mutate(position = ifelse(position == "Other", NA, position)) %>% 
  filter(chamber == Chamber, 
         chair_since_2007 == T,  
         DATE < as.Date("2017-01-01"),
        DATE > as.Date("2007-01-01"),
        assigneddate < as.Date("2017-01-01"),
        terminationdate > as.Date("2007-01-01")) %>%
  select(DATE, chair, position, department, assigneddate, terminationdate, chamber, committee) %>% 
  ggplot() +
  geom_point(
    aes(x = DATE, 
        y = chair),
    shape = 73,
    size=2 
  ) +
  geom_segment(aes(y = chair, yend = chair, 
                   x = assigneddate, xend = terminationdate, 
                   linetype = factor(position)),
               position = position_nudge(y = -0.3)) +
  labs(title = paste(Chamber, "Committee Chairs"),
       y = "", 
       x = "" ) +
  scale_y_discrete(position = "right") +
  theme(
    strip.text.y = element_text(angle = 180, size = 5),
    legend.title = element_blank(),
    axis.text.y = element_text(size=5),
    axis.text.x = element_text(angle = 0)
  ) + 
  facet_grid(committee ~ ., scales = "free_y", space = "free_y", switch = "both") 
```  


## Many letters to FERC are cosigned

```{r cosigned_estimated, eval=FALSE}
#A rough under-estimate based on whether "et al" or "&" appears in the summary:

FERC_letters %>% 
  group_by(ID) %>% 
  top_n(1) %>% 
  mutate(probably_cosigned = ifelse(str_detect(SUBJECT, "et al"), "et al",
                                 ifelse(str_detect(SUBJECT, "&"), "&", " neither"))) %>%
  group_by(year, probably_cosigned) %>% 
  tally %>% 
  ggplot() + 
  aes(x = year, y = n, fill = probably_cosigned) +
  geom_col() 
```

Identified cosigned letters of those coded so far:
```{r cosigned_coded, eval=FALSE}
FERC_letters %>% 
  filter(!is.na(Freelancer)) %>% 
  mutate(cosigned = ifelse(!is.na(Cosigned_House)|!is.na(Cosigned_Senate),
                                 T, F)) %>%
  group_by(year, cosigned) %>% 
  tally %>% 
  ggplot() + 
  aes(x = year, y = n, fill = cosigned) +
  geom_col() 
```

# About FERC 

FERC regulates electricity markets, oil and gas pipelines, and hydropower and gas export terminal projects. 

FERC controls pipeline market entry. 


## Letters on behalf of projects in their districts
TODO

## Letters are on behalf of donors
TODO

# Comparing FERC to other agencies
TODO 


# TO DO 
- Fix Goode, who is being double counted as an R and I
- add company names from company scraper to google sheet
- template to match company names to donation (lobbyview, DIME)
- template match company names to industry codes (center for responsive politics)

# DONE
- add clean text from scraper to google sheet 
- fix clean function to pull and combine new data

# References 

<!--
![Sources of Bureaucratic Delay: A Case Study of FERC Dam Relicensing](https://academic.oup.com/jleo/article/22/1/258/938707)
-->
