---
title: "DOD Independent Study"
subtitle: "Insert Something Insightful Soon"
author: "Fatima Ali"
output:
  #pdf_document
    html_document:
      toc: true
      toc_float: true
      code_folding: hide
editor_options: 
  chunk_output_type: console
---



# Data


```{r data}
load(here("data/all_contacts.RData"))
# one obs per member per letter for all agencies
d <- all_contacts %>% filter(str_detect(agency, "DOD|VA")) ##Added VA and DOD

# how many failed to merge?
d %>% count(is.na())  ##none

d %<>% 
  # FIXME
  # rounding years up is approximate, rewrite to go Nov-Nov?
  #mutate(cycle = congress*2+1786 ) %>% 
  mutate(icpsryear = str_c(icpsr, congress))
```




---

# Outlier
##How do we figure this out??
 
```{r forwards}
# top overall
d %>% count(bioname,party, cqlabel, sort = T) %>% top_n(10, n) %>% kable(caption = "Legislators who wrote the most letters to DOD and VA")


```


---

## By party and majority status




---

# Members

### Senators vs. state population 

```{r population, fig.height= 3.7, fig.width=6}
d %>% 
  filter(chamber == "Senate") %>% 
    group_by(member_state, year, pop2010) %>% summarise(n = n()) %>%
    group_by(member_state, pop2010) %>% summarise(mean = mean(n)) %>% ungroup() %>% 
    ggplot() + 
    geom_point(aes(x = log(pop2010), y = mean), color = "light blue") + 
  geom_smooth(aes(x = log(pop2010), y = mean)) + 
  geom_text(aes(x = log(pop2010), 
                y = mean, 
                label = ifelse(mean > mean(mean)*1.5 | mean < mean(mean)*0.5, 
                               member_state, "")), 
            check_overlap = TRUE, 
            size = 2.5, 
            hjust = 0) + 
  theme_bw() +
  labs(title = "Senator Requests per Year by State Population",
       x = "Log State Population",
       y = "Average Number of Requests per Year")

```

```{r senate_percapita_map}
Chamber = "Senate"

d %>% 
  ungroup() %>%
  filter(chamber == Chamber) %>% 
  group_by(state) %>% summarise(n = n()) %>%
# map_id creates the aesthetic mapping to the state name column
ggplot() + 
  # map points to the fifty_states shape data
  geom_map(aes(map_id = state, fill = n), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "", title = paste("Total Number of Contacts from members of the", Chamber)) +
  scale_fill_viridis_c(option = "C", end = .8) +
  theme(legend.position = "bottom", legend.title = element_blank(),
        panel.background = element_blank()) # + facet_grid(. ~ Constituent)

d %>% 
  ungroup() %>% 
  filter(chamber == Chamber) %>% 
  group_by(state, pop2010) %>% summarise(n = n()) %>% ungroup() %>% 
  mutate(Per_Capita = n/pop2010*1000000) %>% 
  # map_id creates the aesthetic mapping to the state name column in your data
  ggplot() + 
  # map points to the fifty_states shape data
  geom_map(aes(map_id = state, fill = Per_Capita), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "", title = paste("Contacts Per hundred thousand Residents from Members of the", Chamber)) +
  scale_fill_viridis_c(option = "C", end = .8) +
  theme(legend.position = "bottom", 
        legend.title = element_blank() )#+facet_grid(. ~ Constituent)



d  %>% 
  mutate(Per_Capita = n/pop2010*1000000) %>% ##FIXME
  # map_id creates the aesthetic mapping to the state name column in your data
  ggplot() + 
  # map points to the fifty_states shape data
  geom_map(aes(map_id = state, fill = Per_Capita), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "", title = paste("Contacts Per hundred thousand Residents from Members of the", Chamber)) +
  scale_fill_viridis_c(option = "C", end = .8) +
  theme(legend.position = "bottom", 
        legend.title = element_blank() )+
  facet_grid(. ~ Constituent)
```


---

### Members who contact DOD and VA more than average: 

```{r members_barcoded, fig.height=5, fig.width=9}
# barcode plot of committee members 
 
# member by year by agency 
d %>% 
  filter(chamber == Chamber) %>% 
  group_by(name_state) %>% mutate(n = n()) %>% ungroup() %>% 
  filter(n > mean(n)) %>%
  ggplot() +
  geom_point(
    aes(x = DATE, 
        y = reorder(name_state, n) ), 
    # alpha = .6,
    shape = 73,
    size=2
  ) +  
  labs(title = paste(Chamber),
       y = paste("Members by", "Total Number of Letters"), 
       x = "Date of Correspondence" ) +
  theme(
    legend.title = element_blank(),
    axis.text.y = element_text(size=5)
  ) + 
    guides(fill=guide_legend(ncol=1)) 


Chamber <- "House" # "House" #  
 
# member by year by agency 
d %>% 
  filter(chamber == Chamber) %>% 
  group_by(name_state) %>% mutate(n = n()) %>% ungroup() %>% 
  filter(n > mean(n)) %>%
  ggplot() +
  geom_point(
    aes(x = DATE, 
        y = reorder(name_state, n) ), 
    # alpha = .6,
    shape = 73,
    size=2
  ) +  
  labs(title = paste(Chamber),
       y = paste("Members by", "Total Number of Letters"), 
       x = "Date of Correspondence" ) +
  theme(
    legend.title = element_blank(),
    axis.text.y = element_text(size=5)
  ) + 
    guides(fill=guide_legend(ncol=1)) 
```

```{r ferc_vs_all_rate}
all_contacts %>%
  filter(congress >109) %>% 
  mutate(FERC = agency == "DOD"|"VA") %>%
  count(chamber, DOD|VA, name_state, state) %>%
  spread(key = "DOD"|"VA", value = "n", 0) %>% 
  mutate(ShareToDOD_VA = round(`TRUE`/(`TRUE`+`FALSE`),2) ) %>% 
  arrange(-ShareToDOD_VA) %>% 
  mutate(total = `TRUE` + `FALSE`) %>% 
  select(name_state, chamber, total, ShareToDOD_VA) %>% 
  filter(ShareToDOD_VA>.3) %>%
  knitr::kable(caption = "Members who contact DOD and VA more, relative to other agencies" )


all_contacts %>% 
  filter(congress >109) %>% 
  mutate(FERC = agency == "DOD"|"VA") %>%
  count(chamber, congress, FERC, name_state, state) %>%
  spread(key = "DOD"|"VA", value = "n", 0) %>% 
  mutate(ShareToDOD_VA = round(`TRUE`/(`TRUE`+`FALSE`),2) ) %>% 
  arrange(-ShareToDOD_VA) %>% 
  mutate(total = `TRUE` + `FALSE`) %>% 
  select(name_state, chamber, congress, total, ShareToDOD_VA) %>% 
    filter(total >10) %>% 
  top_n(10) %>%
  knitr::kable(caption = "Members who contact DOD and VA more, relative to other agencies")
```


### Multivariate models 
```{r full-model, fig.height=1}
# Full model, all letters
mAll_Full <- glm(total_letters ~ PAC_100k + party_name, 
                 data = letters_money %>% 
                        filter(industry == "energy") %>% 
                        filter(party_name != "Independent") %>% 
                        select(icpsr, congress, PAC_100k, chamber,party_name, total_letters) %>%
                      distinct(),
            family = poisson)

# tidy(mAll_Full)

mplot(mAll_Full)+
  labs(x="", y="Additional letters per congress")

# Full model with interaction:
mAll_Fullx <- glm(total_letters ~ PAC_100k*party_name, 
                                   data = letters_money %>% 
                        filter(industry == "energy") %>% 
                        filter(party_name != "Independent") %>% 
                        select(icpsr, congress, PAC_100k, chamber,party_name, total_letters) %>%
                      distinct(),
            family = poisson)
# tidy(mAll_Fullx)

mplot(mAll_Fullx)+
  labs(x="", y="Additional letters per congress")



# Full model, pro business letters 
mPro_Full <- glm(ProBusiness_Letters ~ PAC_100k + party_name, 
                                  data = letters_money %>% 
                        filter(industry == "energy") %>% 
                        filter(party_name != "Independent") %>% 
                        select(icpsr, congress, PAC_100k, chamber,party_name, ProBusiness_Letters) %>%
                      distinct(),
            family = poisson)

# tidy(mPro_Full)

mplot(mPro_Full)+
  labs(x="", y="Additional letters per congress")

# Full model with interaction:
mPro_Fullx <- glm(ProBusiness_Letters ~ PAC_100k * party_name, 
                                  data = letters_money %>% 
                        filter(industry == "energy",
                               party_name != "Independent",
                               !is.na(ProBusiness_Letters)) %>% 
                        select(icpsr, congress, PAC_100k, chamber,party_name, ProBusiness_Letters) %>%
                      distinct(),
            family = poisson)

# tidy(mPro_Fullx)

mplot(mPro_Fullx)+
  labs(x="", y="Additional letters per congress")


mAnti_Full <- glm(AntiBusiness_Letters ~ PAC_100k + party_name, 
                                  data = letters_money %>% 
                        filter(industry == "energy") %>% 
                        filter(party_name != "Independent") %>% 
                        select(icpsr, congress, PAC_100k, party_name,chamber, AntiBusiness_Letters) %>%
                      distinct(),
            family = poisson)

# tidy(mAnti_Full)

mplot(mAnti_Full)+
  labs(x="", y="Additional letters per congress")

# full model with interaction 
mAnti_Fullx <- glm(AntiBusiness_Letters ~ PAC_100k * party_name, 
                                  data = letters_money %>% 
                        filter(industry == "energy") %>% 
                        filter(party_name != "Independent") %>% 
                        select(icpsr, congress, PAC_100k, party_name,chamber, AntiBusiness_Letters) %>%
                      distinct(),
            family = poisson)

letters_money %>% 
                        filter(industry == "energy") %>% 
                        filter(party_name != "Independent") %>% 
                        #filter(!is.na(AntiBusiness_Letters)) %>% 
                        select(icpsr, congress, PAC_100k, party_name,chamber, AntiBusiness_Letters, letter_position) %>%
                      distinct() %>% count(letter_position) #%>% filter(is.na(icpsr)|is.na(congress)|is.na(PAC_100k)|is.na(party_name)|is.na(AntiBusiness_Letters)&is.na(ProBusiness_Letters))

# tidy(mAnti_Fullx)
mplot(mAnti_Fullx)+
  labs(x="", y="Additional letters per congress")

# FULL MODEL WITH NON- CONSTITUENT 
# FIXME
#mNonConstituent_Fullx <- glm(NonConstituent_Letters ~ PAC_contributions*party, data = NonConstituent_letters_money %>% filter(!party %in% c("NA","(I)", "Independent"))%>% mutate(PAC_contributions = PAC_contributions/100000), family = "poisson" )  
#tidy(mNonConstituent_Fullx)
#mplot(mNonConstituent_Fullx)+labs(x="", y="Additional non-constituent letters per congress")
```



#### Edit Everything Below Accordingly
### Party
```{r models-party, fig.height=2, results='hide'}
## With party IV 
models <- tidy(mProParty) %>% 
  mutate(model = "Pro-business Letters per Cycle") %>%
  full_join(tidy(mAntiParty) %>%
              mutate(model = "Anti-business Letters per Cycle")) %>%
  # mutate(term = str_replace(term, "party\\(R\\)", "Republican")) %>% 
  filter(term != "party(I)")

dplot(models) + 
    labs(x = "Additional letters per cycle")

write_lines(
  stargazer::stargazer(mProParty, mAntiParty, float=F),
  path = here("FERC/tables/mProParty-mAntiParty.tex"))

table <- stargazer(mProParty, mAntiParty, 
                type = "html",
                notes = "FERC/tables/mProParty-mAntiParty.tex")
```

```{r, results="asis"}
htmltools::HTML(table)
```



### Univariate models 
```{r models-ALL, fig.height=2, results='hide'}
# All models 
write_lines(
  stargazer::stargazer(mAll, mPro, mAnti,mNonConstituent, mProLog, mAntiLog, mProParty, mProTotal, mAntiTotal, mAntiParty, float = F),
  path = here("FERC/tables/mUnivariate.tex"))

table <-stargazer(mAll, mPro, mAnti, mNonConstituent, mProLog, mAntiLog, mProParty, mProTotal, mAntiTotal, mAntiParty, 
                type = "html",
                notes = "FERC/tables/mUnivariate.tex")
```

```{r, results="asis"}
htmltools::HTML(table)
```



### Multivariate Models
```{r models-full, fig.height=2, results='hide'}
## Full models
models <- tidy(mAll_Full) %>% 
  mutate(model = "Total Letters per Cycle") %>%
  full_join(tidy(mPro_Full) %>%
              mutate(model = "Pro-business Letters per Cycle")) %>%
  full_join(tidy(mAnti_Full) %>%
              mutate(model = "Anti-business Letters per Cycle"))
dplot(models) + 
    labs(x = "Additional letters per cycle")

## Full models + interactions
models <- tidy(mAll_Full) %>% 
  mutate(model = "Total Letters per Cycle") %>%
  full_join(tidy(mPro_Full) %>%
              mutate(model = "Pro-business Letters per Cycle")) %>%
  full_join(tidy(mPro_Fullx) %>% mutate(model = "Pro-business Letters per Cycle, with interaction")) %>%
  full_join(tidy(mAnti_Full) %>%
              mutate(model = "Anti-business Letters per Cycle")) %>%
  full_join(tidy(mAnti_Fullx) %>% mutate(model = "Anti-business Letters per Cycle, with interaction")) # %>%  mutate(term = str_replace(term, "party\\(R\\)", "Republican"))

dplot(models) + 
    labs(x = "Additional letters per cycle")

write_lines(
  stargazer::stargazer(mAll_Full, mAll_Fullx, mPro_Full, mAnti_Full,mPro_Fullx, mAnti_Fullx, float=F),
  path = here("FERC/tables/mFull.tex"))

table <- stargazer(mPro_Full, mAnti_Full, mPro_Fullx, mAnti_Fullx,
                type = "html",
                notes = "FERC/tables/mFull.tex")

table <- stargazer(mPro_Full, mAnti_Full, mPro_Fullx, mAnti_Fullx,
                type = "html",
                notes = "FERC/tables/mFull.tex")
```

```{r, results="asis"}
htmltools::HTML(table)
```



# About DOD and VA



## Letters on behalf of projects in their districts
###Fix to make relevant

```{r}
d %>% 
  mutate(Place_District = tolower(Place_District)) %>% 
  # FIXME 
  # dropping odd observations, will correct in DOE_FERC.R script 
  filter(Place_District %in% c("yes", "no", NA)) %>% 
  filter(letter_position %in% c("AntiBusiness", "ProBusiness")) %>% 
  filter(Constituent != "Not coded") %>% 
  count(Place_District, letter_position, Constituent) %>% 
  ggplot() +
  aes(x = Place_District, y = n, fill = letter_position) +
  geom_col() + 
  facet_grid(Constituent ~ .)+ 
  labs(x = "Is the proposed project in the member's district?",
       y = "Number of letters",
       fill = "")
```





