---
title: "policyFigs"
output: html_document
---

```{r setup, include=FALSE}
requires <- c("tidyr", "broom", "knitr","ineq", "dplyr", "ggplot2", "magrittr", "stargazer", "maps", "fiftystater", "mapproj", "dotwhisker")
  to_install <- c(requires %in% rownames(installed.packages()) == FALSE)
  install.packages(c(requires[to_install], "NA"), repos = "https://cloud.r-project.org/" )
  library(tidyr)
  library(ineq)
  library(dplyr)
  library(ggplot2)
  library(magrittr)
  library(stargazer)
  library(maps)
  #library(fiftystater)
  library(mapproj)
  library(knitr)
  library(broom)
  library(dotwhisker)

load("correspondence.RData")

all <- df %>% filter(year < 2018) %>% 
  mutate(POLICY_EVENT  = {gsub(";.*|/.*|\\(.*|\\?|MAYBE |PROBABLY |POSSIBLE |POSSIBLY ","", toupper(.$POLICY_EVENT), ignore.case = T)} ) %>% # %>% filter(congress != 115
mutate(Policy_Type = ifelse(POLICY_EVENT == "LEGISLATION" | POLICY_EVENT == "APPROPRIATION"| POLICY_EVENT=='EARMARK', 'LEGISLATION', NA)) %>% 
  mutate(Policy_Type = ifelse(POLICY_EVENT == "RULE", 'EXECUTIVE', Policy_Type))

leg <- filter(all, Policy_Type == "LEGISLATION") 
exe <- filter(all, Policy_Type == "EXECUTIVE")
```

Completeness by Policy Event
```{r cars}
df %>% 
  filter(!is.na(POLICY_EVENT)) %>% 
  mutate(POLICY_EVENT  = {gsub(";.*|/.*|\\(.*|\\?|MAYBE |PROBABLY |POSSIBLE |POSSIBLY ","", toupper(.$POLICY_EVENT), ignore.case = T)} ) %>%
  mutate(total = n()) %>% 
  group_by(POLICY_EVENT) %>% mutate(nPE = n()) %>% ungroup() %>%
  filter(nPE > 10) %>% 
  # mutate(total = sum(nPE)) %>% 
  mutate(percent = paste(POLICY_EVENT, 100*round(nPE/total, 3), "%")) %>% 
  group_by(agency) %>% mutate(n = n()) %>% ungroup() %>%
  ggplot() + 
  geom_point(aes(x = DATE, y = reorder(agency, n), color = percent), #gsub(";.*|/.*|\\(.*", POLICY_EVENT))), 
             #alpha = .4,
             shape = 73,
             size=2) + 
  labs(x = "Date of Correspondence",
       y = "Agency, N",
       title = paste("Coded Observations, N =", sum(!is.na(df$POLICY_EVENT) ) ) ) +
  facet_grid(complete ~ ., scales = "free_y", space = "free_y") + 
  theme(panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x.top = element_text())
```

Completeness by Policy Type (Executive vs. Legistaltion)
```{r cars}
all %>% 
  filter(!is.na(POLICY_EVENT)) %>% 
  filter(Policy_Type == "LEGISLATION" | Policy_Type == "EXECUTIVE") %>% 
  mutate(total = n()) %>% 
  group_by(Policy_Type) %>% mutate(nPE = n()) %>% ungroup() %>%
  filter(nPE > 10) %>% 
  #mutate(total = sum(nPE)) %>% 
  mutate(percent = paste(Policy_Type, 100*round(nPE/total, 3), "%")) %>% 
  group_by(agency) %>% mutate(n = n()) %>% ungroup() %>%
  ggplot() + 
  geom_point(aes(x = DATE, y = reorder(agency, n), color = percent), #gsub(";.*|/.*|\\(.*", POLICY_EVENT))), 
             #alpha = .4,
             shape = 73,
             size=2) + 
  labs(x = "Date of Correspondence",
       y = "Agency, N",
       title = paste("Coded Observations, N =", sum(!is.na(all$Policy_Type) ) ) ) +
  facet_grid(complete ~ ., scales = "free_y", space = "free_y") + 
  theme(panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x.top = element_text())
```