---
title: "Who Gets Constituent Service?"
subtitle: 
author: "Rochelle Snyder, Eleanor Neff Powell, Devin Judge-Lord, Justin Grimmer"
output:
  #pdf_document
    html_document:
      #toc: true
      #toc_float: true
      code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r global.options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      cache = FALSE, 
                      fig.width=8.5, 
                      split = T,
                      fig.align = 'center', 
                      fig.path='figs/',
                      warning=FALSE, 
                      message=FALSE)
```

```{r setup}
source(here::here("setup.R"))

library(ggplot2); theme_set(theme_bw())
  options(
    ggplot2.continuous.color = "viridis",
    ggplot2.continuous.fill = "viridis"
  )
  scale_color_discrete <- function(...)
    scale_color_viridis_d(...)
  scale_fill_discrete <- function(...)
    scale_fill_viridis_d(...)
```


```{r data}
load(here::here("data/all_contacts.Rdata"))
d <- all_contacts

d %<>% 
    mutate(TYPE = replace_na(TYPE, "NA"),
           constituent = ifelse(TYPE == 1, "Indiv. Constituent Service", "Other")) %>% 
  add_count(icpsr, constituent, agency, year, name = "n_per_year_agency") %>% 
  add_count(icpsr, constituent, year, name = "n_per_year") %>% 
  mutate(percent_to_agency = (n_per_year_agency/n_per_year)*100)


d1 <- d %>% 
  filter(year > 2006, year <2018) %>% 
  select(icpsr, year, agency, constituent, n_per_year_agency, n_per_year, percent_to_agency) %>%
  filter(agency %in% c("VA", #"SSA", 
                       "DHHS_CMS", "DHHS_CDC", "DHHS_HRSA")) %>% distinct()
```

## Percent of legislator contacts per agency 2007-2017
```{r percent_to_agency, fig.width=8}
d1 %>% 
  ggplot() +
  aes(x = year, y = percent_to_agency, color = constituent) +
  #geom_line(aes(group= icpsr), alpha = .1) + 
  geom_smooth() + 
  labs(x = "", y = "Percent of contacts", color = "") + 
  facet_wrap(. ~ agency, scales = "free_y", nrow = 1) +
  scale_x_continuous(breaks = seq(2007,2017, 2)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Number of legislator contacts per agency 2007-2017
```{r n_per_year_agency, fig.width=8}
d1 %>%
  ggplot() +
  aes(x = year, color = constituent, y = n_per_year_agency) +
  #geom_line(aes(group= icpsr), alpha = .1) + 
  geom_smooth() + 
  labs(x = "", y = "Number of contacts", color = "") + 
  facet_wrap(. ~ agency, scales = "free_y", nrow = 1) +
  scale_x_continuous(breaks = seq(2007,2017, 2)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```